// Mocks generated by Mockito 5.3.2 from annotations
// in ditonton/test/presentation/provider/tvshow/tvshow_list_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:ditonton/common/failure.dart' as _i6;
import 'package:ditonton/domain/entities/tvshow/tvshow.dart' as _i7;
import 'package:ditonton/domain/repositories/tvshow_repository.dart' as _i2;
import 'package:ditonton/domain/usecases/tvshow/get_on_the_air_tvshows.dart'
    as _i4;
import 'package:ditonton/domain/usecases/tvshow/get_popular_tvshows.dart'
    as _i8;
import 'package:ditonton/domain/usecases/tvshow/get_top_rated_tvshows.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvshowRepository_0 extends _i1.SmartFake
    implements _i2.TvshowRepository {
  _FakeTvshowRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetOnTheAirTvshows].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOnTheAirTvshows extends _i1.Mock
    implements _i4.GetOnTheAirTvshows {
  MockGetOnTheAirTvshows() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvshowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvshowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvshowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Tvshow>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Tvshow>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Tvshow>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Tvshow>>>);
}

/// A class which mocks [GetPopularTvshows].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTvshows extends _i1.Mock implements _i8.GetPopularTvshows {
  MockGetPopularTvshows() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvshowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvshowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvshowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Tvshow>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Tvshow>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Tvshow>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Tvshow>>>);
}

/// A class which mocks [GetTopRatedTvshows].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTvshows extends _i1.Mock
    implements _i9.GetTopRatedTvshows {
  MockGetTopRatedTvshows() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvshowRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvshowRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvshowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Tvshow>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Tvshow>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Tvshow>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Tvshow>>>);
}
