// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD42h3QJuxCwXdb1EubxyTF-XUlo5k1uFs',
    appId: '1:420555604871:web:2f5c15b40cb357d9068922',
    messagingSenderId: '420555604871',
    projectId: 'ditonton-46d80',
    authDomain: 'ditonton-46d80.firebaseapp.com',
    storageBucket: 'ditonton-46d80.appspot.com',
    measurementId: 'G-C0YHWEZBYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFu4hRP44YpeTfsXA_mzI3TNb30ZzikbA',
    appId: '1:420555604871:android:d6443ce5310fcf99068922',
    messagingSenderId: '420555604871',
    projectId: 'ditonton-46d80',
    storageBucket: 'ditonton-46d80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE_GxVW83-XAbowh81YCmCkBi2Y5H7plA',
    appId: '1:420555604871:ios:d58fc1e4ec4aa289068922',
    messagingSenderId: '420555604871',
    projectId: 'ditonton-46d80',
    storageBucket: 'ditonton-46d80.appspot.com',
    iosClientId: '420555604871-hnivt6uj9fnnrn87939n8tsqgtuq6stj.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
