// Mocks generated by Mockito 5.3.2 from annotations
// in ditonton/test/helpers/test_helper_tvshow.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i16;
import 'dart:typed_data' as _i17;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/common/failure.dart' as _i7;
import 'package:ditonton/data/datasources/db/tvshow_database_helper.dart'
    as _i14;
import 'package:ditonton/data/datasources/tvshow/tvshow_local_data_source.dart'
    as _i12;
import 'package:ditonton/data/datasources/tvshow/tvshow_remote_data_source.dart'
    as _i10;
import 'package:ditonton/data/models/tvshow/tvshow_detail_model.dart' as _i3;
import 'package:ditonton/data/models/tvshow/tvshow_model.dart' as _i11;
import 'package:ditonton/data/models/tvshow/tvshow_table.dart' as _i13;
import 'package:ditonton/domain/entities/tvshow/tvshow.dart' as _i8;
import 'package:ditonton/domain/entities/tvshow/tvshow_detail.dart' as _i9;
import 'package:ditonton/domain/repositories/tvshow_repository.dart' as _i5;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvshowDetailResponse_1 extends _i1.SmartFake
    implements _i3.TvshowDetailResponse {
  _FakeTvshowDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_3 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvshowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvshowRepository extends _i1.Mock implements _i5.TvshowRepository {
  MockTvshowRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>> getOnTheAirTvshows() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnTheAirTvshows,
          [],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>>.value(
                _FakeEither_0<_i7.Failure, List<_i8.Tvshow>>(
          this,
          Invocation.method(
            #getOnTheAirTvshows,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>> getPopularTvshows() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvshows,
          [],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>>.value(
                _FakeEither_0<_i7.Failure, List<_i8.Tvshow>>(
          this,
          Invocation.method(
            #getPopularTvshows,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>> getTopRatedTvshows() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvshows,
          [],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>>.value(
                _FakeEither_0<_i7.Failure, List<_i8.Tvshow>>(
          this,
          Invocation.method(
            #getTopRatedTvshows,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, _i9.TvshowDetail>> getTvshowDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvshowDetail,
          [id],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, _i9.TvshowDetail>>.value(
                _FakeEither_0<_i7.Failure, _i9.TvshowDetail>(
          this,
          Invocation.method(
            #getTvshowDetail,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i9.TvshowDetail>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>>
      getTvshowRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getTvshowRecommendations,
              [id],
            ),
            returnValue:
                _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>>.value(
                    _FakeEither_0<_i7.Failure, List<_i8.Tvshow>>(
              this,
              Invocation.method(
                #getTvshowRecommendations,
                [id],
              ),
            )),
          ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>> searchTvshow(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvshow,
          [query],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>>.value(
                _FakeEither_0<_i7.Failure, List<_i8.Tvshow>>(
          this,
          Invocation.method(
            #searchTvshow,
            [query],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, String>> saveWatchlistTvshow(
          _i9.TvshowDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlistTvshow,
          [tv],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, String>>.value(
            _FakeEither_0<_i7.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlistTvshow,
            [tv],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, String>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, String>> removeWatchlistTvshow(
          _i9.TvshowDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlistTvshow,
          [tv],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, String>>.value(
            _FakeEither_0<_i7.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlistTvshow,
            [tv],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, String>>);
  @override
  _i6.Future<bool> isAddedToWatchlistTvshow(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlistTvshow,
          [id],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>> getWatchlistTvshows() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvshows,
          [],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>>.value(
                _FakeEither_0<_i7.Failure, List<_i8.Tvshow>>(
          this,
          Invocation.method(
            #getWatchlistTvshows,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.Tvshow>>>);
}

/// A class which mocks [TvshowRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvshowRemoteDataSource extends _i1.Mock
    implements _i10.TvshowRemoteDataSource {
  MockTvshowRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i11.TvshowModel>> getOnTheAirTvshows() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnTheAirTvshows,
          [],
        ),
        returnValue:
            _i6.Future<List<_i11.TvshowModel>>.value(<_i11.TvshowModel>[]),
      ) as _i6.Future<List<_i11.TvshowModel>>);
  @override
  _i6.Future<List<_i11.TvshowModel>> getPopularTvshows() => (super.noSuchMethod(
        Invocation.method(
          #getPopularTvshows,
          [],
        ),
        returnValue:
            _i6.Future<List<_i11.TvshowModel>>.value(<_i11.TvshowModel>[]),
      ) as _i6.Future<List<_i11.TvshowModel>>);
  @override
  _i6.Future<List<_i11.TvshowModel>> getTopRatedTvshows() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvshows,
          [],
        ),
        returnValue:
            _i6.Future<List<_i11.TvshowModel>>.value(<_i11.TvshowModel>[]),
      ) as _i6.Future<List<_i11.TvshowModel>>);
  @override
  _i6.Future<_i3.TvshowDetailResponse> getTvshowDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvshowDetail,
          [id],
        ),
        returnValue: _i6.Future<_i3.TvshowDetailResponse>.value(
            _FakeTvshowDetailResponse_1(
          this,
          Invocation.method(
            #getTvshowDetail,
            [id],
          ),
        )),
      ) as _i6.Future<_i3.TvshowDetailResponse>);
  @override
  _i6.Future<List<_i11.TvshowModel>> getTvshowRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvshowRecommendations,
          [id],
        ),
        returnValue:
            _i6.Future<List<_i11.TvshowModel>>.value(<_i11.TvshowModel>[]),
      ) as _i6.Future<List<_i11.TvshowModel>>);
  @override
  _i6.Future<List<_i11.TvshowModel>> searchTvshow(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvshow,
          [query],
        ),
        returnValue:
            _i6.Future<List<_i11.TvshowModel>>.value(<_i11.TvshowModel>[]),
      ) as _i6.Future<List<_i11.TvshowModel>>);
}

/// A class which mocks [TvshowLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvshowLocalDataSource extends _i1.Mock
    implements _i12.TvshowLocalDataSource {
  MockTvshowLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> insertWatchlistTvshow(_i13.TvshowTable? tvshow) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlistTvshow,
          [tvshow],
        ),
        returnValue: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);
  @override
  _i6.Future<String> removeWatchlistTvshow(_i13.TvshowTable? tvshow) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlistTvshow,
          [tvshow],
        ),
        returnValue: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);
  @override
  _i6.Future<_i13.TvshowTable?> getTvshowById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvshowById,
          [id],
        ),
        returnValue: _i6.Future<_i13.TvshowTable?>.value(),
      ) as _i6.Future<_i13.TvshowTable?>);
  @override
  _i6.Future<List<_i13.TvshowTable>> getWatchlistTvshows() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvshows,
          [],
        ),
        returnValue:
            _i6.Future<List<_i13.TvshowTable>>.value(<_i13.TvshowTable>[]),
      ) as _i6.Future<List<_i13.TvshowTable>>);
}

/// A class which mocks [DatabaseHelperTvshow].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelperTvshow extends _i1.Mock
    implements _i14.DatabaseHelperTvshow {
  MockDatabaseHelperTvshow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i15.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i6.Future<_i15.Database?>.value(),
      ) as _i6.Future<_i15.Database?>);
  @override
  _i6.Future<int> insertWatchlistTvshow(_i13.TvshowTable? tvshow) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlistTvshow,
          [tvshow],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);
  @override
  _i6.Future<int> removeWatchlistTvshow(_i13.TvshowTable? tvshow) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlistTvshow,
          [tvshow],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);
  @override
  _i6.Future<Map<String, dynamic>?> getTvshowById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvshowById,
          [id],
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);
  @override
  _i6.Future<List<Map<String, dynamic>>> getWatchlistTvshows() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvshows,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i16.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i16.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i16.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i16.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);
  @override
  _i6.Future<_i17.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i17.Uint8List>.value(_i17.Uint8List(0)),
      ) as _i6.Future<_i17.Uint8List>);
  @override
  _i6.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i6.Future<_i4.StreamedResponse>.value(_FakeStreamedResponse_3(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i6.Future<_i4.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
